s = set()
n1 = int(input("Enter number1: "))
s.add(n1)
n2 = int(input("Enter number2: "))
s.add(n2)
n3 = int(input("Enter number3: "))
s.add(n3)
n4 = int(input("Enter number4: "))
s.add(n4)
n5 = int(input("Enter number5: "))
s.add(n5)
n6 = int(input("Enter number6: "))
s.add(n6)
n7 = int(input("Enter number7: "))
s.add(n7)
n8 = int(input("Enter number8: "))
s.add(n8)
print(s)