fruits = []

a = input("Enter the name of fruit :")
fruits.append(a)
b = input("Enter the name of fruit :")
fruits.append(b)
c = input("Enter the name of fruit :")
fruits.append(c)
d = input("Enter the name of fruit :")
fruits.append(d)
e = input("Enter the name of fruit :")
fruits.append(e)
f = input("Enter the name of fruit :")
fruits.append(f)
g = input("Enter the name of fruit :")
fruits.append(g)
print(fruits)